"""Initial migration

Revision ID: 96a8548d410b
Revises: 
Create Date: 2024-12-04 19:56:16.340090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96a8548d410b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('company_name', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('single_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=250), nullable=False),
    sa.Column('electricity_bill', sa.Float(), nullable=False),
    sa.Column('gas_bill', sa.Float(), nullable=False),
    sa.Column('fuel_bill', sa.Float(), nullable=False),
    sa.Column('waste_generate', sa.Float(), nullable=False),
    sa.Column('recycled_waste', sa.Float(), nullable=False),
    sa.Column('yearly_travel', sa.Float(), nullable=False),
    sa.Column('fuel_usage', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_name')
    )
    op.create_table('final_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('single_id', sa.Integer(), nullable=False),
    sa.Column('energy_usage', sa.Float(), nullable=False),
    sa.Column('waste', sa.Float(), nullable=False),
    sa.Column('business_travel', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['single_id'], ['single_value.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('final_values')
    op.drop_table('single_value')
    op.drop_table('user')
    # ### end Alembic commands ###
